name: Generate Snake Game

on:
  schedule:  # Executes the workflow on a schedule
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v2

      # Step 2: Generate the contribution snake
      - uses: Platane/snk@v3
        with:
          github_user_name: Tomrm96  # Your GitHub username

          # List of files to generate. Each output can be customized.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Push the generated files to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Branch to push the generated snake files
          build_dir: dist        # Directory where the snake files are stored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
