name: Update Recent Activity


on:
  schedule:
    - cron: '*/60 * * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      
      - uses: jamesgeorge007/github-activity-readme@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Updated recent activity"
          git push
